config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :books
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :unauthenticated, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }



  # Change root path when user is signed in
  authenticated :user do
    namespace :example do
      resources :home do
        # I normally would move people to it's own controller, but wanted to use "collection" for this demo
        collection do
          get :people
        end
      end
      resources :homeworld
    end
    root to: 'authenticated#index', as: :authenticated_root
  end

  root to: 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/example/home_controller.rb
class Example::HomeController < AuthenticatedController
  def index; end

  def people
    people = Swapi.get_all(:people)&.dig('results')
    @people = people&.map { |person| Person.new person } || []
  end
end

app/controllers/example/homeworld_controller.rb
class Example::HomeworldController < AuthenticatedController
  def show
    result = Swapi.get_planet params[:id]
    @homeworld = Homeworld.new result
  end
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/views/example/home/index.html.erb
<div data-controller="example">
  <hr/>
  <div class="row">
    <div class="col-8">
      <h1>Star Wars Characters</h1>
      <%= turbo_frame_tag :people, src: people_example_home_index_path do %>
        People have not been loaded yet
      <% end %>
    </div>
    <div class="col-4" style="border-left: 1px solid black">
      <h1>Homeworld</h1>
      <%= turbo_frame_tag :home_world, data: { example_target: :homeworld, base_path: example_homeworld_index_path } do %>
        Home world has not been loaded yet
      <% end %>
    </div>
  </div>
</div>

app/views/example/home/people.html.erb
<%= turbo_frame_tag :people do %>
  <%# Example of rendering array of objects using associated partial view %>
  <%= render @people %>
<% end %>